---
title: "Learning Diary - Week 2"
subtitle: "Sentinel-2"
author: "Nanami Tsuchiyama"
institute: "UCL CASA MSc Urban Spatial Science"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      
---

class: inverse, center, middle

# add picture of sentinel-2

---


# Summary 

## Sentinel-2 - overview

.pull-left[
Sentinel 2 is a "wide swath, high resolution, multi-spectral mission" operated by the European Space Agency (ESA) []. A total of 13 bands with 3 different spatial resolutions are sampled by the MultiSpectral Instrument (MSI) it carries - 4 bands at 10m, 6 bands at 20m, 3 bands at 60m (ibid.). 
.footnote[]
]

---

# Summary 

## Sentinel-2 - coverage

There are two identical satelites, each with a swath width<sup>1</sup> of 290km: Sentinel 2A (launched 23)[] and Sentinel 2B (launched ) [provide reference]. The following areas have been listed as being covered with the satelites (ibid.). 

- all continental areas (including inland waters) between latitudes 84N and 56S
- all coastal waters up to 20km from shore 
- all islands that are part of the EU
- the Mediterranean Sea
- all closed seas

---

# Summary

## Sentinel-2 - Data products 

The Level-1B product provides Top-of-atmospher radiance in sensor geometry. A single granule On the other hand, the Level-1C 

---

# Applications

## Regional Policy

One of the notable policy applications of Sentinel Data is for the Senitnels for Common Agriculture Policy (Sen4CAP) project. The CAP of the EU is 


The SEN4CAP is operated by the European Space Agency along with DG-Agri, DG-Grow and DG-JRC of the European Commission. The monitoring approach has allowed for the replacement of physical visits of farms which was stressful for the farmers by data from the Copernicus Sentinels. As 

---

# Applications 

## International Policy data 

Sentinel 2 has been 

As the Sentinel-2 mission is

One 
Although the data from Senitnel has been primarily utilised for agricultural purposes in academic research, such as mapping crop types  

The study conducted by 

---

# Reflections

Researching about the Sentinel-2 provided me a better understanding of how the sensor operates. This allows for a more sophisticated interpretation of the data that is produced by the sensor. 

I found the application of the data for both a EU-wide policy and international space particularly interesting. The exploration of outer space including the launch of satelites  space nationalism. The whole operation of Sentinel 2 in the first place may be thought of a representation of "Europeanisation" of the space industry. At the same time, the utility of remote sensing images for global frameworks is being increasingly recognised, as demonstrated in the policy applications for the SDGs. The various interests involved in both the production and usage of remote sensing imagery is 
---

# References


